# Generated by Django 5.2.15 on 2026-06-23 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('cbc', 'Complete Blood Count'), ('lft', 'Liver Function Test'), ('kft', 'Kidney Function Test'), ('lipid', 'Lipid Profile'), ('thyroid', 'Thyroid Profile'), ('glucose', 'Blood Glucose'), ('urine', 'Urine Analysis'), ('electrolytes', 'Electrolytes'), ('cardiac', 'Cardiac Markers'), ('other', 'Other')], default='cbc', max_length=20)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ai_interpretation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.patient')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='LabParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('critical_low', 'Critical Low'), ('critical_high', 'Critical High')], default='normal', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='reports.labreport')),
            ],
        ),
    ]
