# Generated by Django 5.2.15 on 2026-06-22 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('general', 'General Physician'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('surgery', 'Surgery'), ('oncology', 'Oncology'), ('other', 'Other')], default='general', max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('license_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('hospital_address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('available_days', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
