# Generated by Django 5.2.15 on 2026-06-24 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('bed_number', models.CharField(blank=True, max_length=20)),
                ('chief_complaints', models.TextField()),
                ('medical_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('diagnosis', models.TextField()),
                ('differential_diagnosis', models.TextField(blank=True)),
                ('investigations', models.TextField(blank=True)),
                ('imaging_results', models.TextField(blank=True)),
                ('procedures_performed', models.TextField(blank=True)),
                ('treatment_given', models.TextField(blank=True)),
                ('blood_transfusions', models.TextField(blank=True)),
                ('hospital_course', models.TextField()),
                ('complications', models.TextField(blank=True)),
                ('condition_at_discharge', models.CharField(choices=[('stable', 'Stable'), ('improved', 'Improved'), ('critical', 'Critical'), ('deceased', 'Deceased'), ('transferred', 'Transferred')], default='stable', max_length=20)),
                ('discharge_medications', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('diet_instructions', models.TextField(blank=True)),
                ('activity_restrictions', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('ai_narrative', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='discharge_summaries/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_summaries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summaries', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Discharge Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
